// =============================
// components/our-team/data.ts
// =============================
import type { TeamMember, Trainer, TeamLeaders } from "./types";


export const BRAND = "#ff8c00"; // Cinute Digital brand


export const teamLeaders: TeamLeaders[] = [
    {
        id: "1",
        name: "Sandeep Maske",
        title: "Founder & Chief Mentor",
        role: "Leadership",
        expertise: ["Software Testing", "Automation", "Career Mentorship"],
        bio: "EdTech leader with a decade of experience enabling learners to build industry-ready skills through hands-on projects and mentor-led learning.",
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/sandeep-maske-img.webp",
        linkedin: "https://www.linkedin.com/in/sandeepmaske",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Built 1k+ careers", "ISO-aligned delivery"],

    },
    {
        id: "2",
        name: "Santosh Kakade",
        title: "QA & Digital Solutions",
        role: "Operations",
        expertise: ["QA", "Digital Solutions"],
        bio: "Santosh Kakade, With 17+ years in QA & digital solutions, lead TESTRIQ QA Lab & Cinute Digital, delivering top-tier testing services and upskilling professionals in tech.",
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/Santosh_Kakade.webp",
        linkedin: "https://www.linkedin.com/in/santoshkakade/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Built 1k+ careers", "ISO-aligned delivery"],

    },
    {
        id: "3",
        name: "Goutam Mishra",
        title: "Head of QA and BD",
        role: "Software Testing & BD",
        expertise: ["Software Testing", "BD"],
        bio: "Goutam Mishra, With 20+ years in tech, excel in QA, testing, and project management, mentoring QA professionals while ensuring top-tier software quality across platforms.",
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/Goutam_Mishra.webp",
        linkedin: "https://www.linkedin.com/in/goutam-mishra-96194117/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Built 1k+ careers", "ISO-aligned delivery"],

    },
    {
        id: "4",
        name: "Shoeb Shaikh",
        title: "Head - Learning and Development",
        role: "Software Testing and Data Science Expert",
        expertise: ["Software Testing", "Data Science Expert"],
        bio: "Shoeb Shaikh is a seasoned Software Testing and Data Science Expert and a Mentor with over 14 years of experience in the field. Specialist in designing and managing processes, and leading high-performing teams to deliver impactful results.",
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/ShoebShaikh.webp",
        linkedin: "https://www.linkedin.com/in/ishaikhshoeb/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Built 1k+ careers", "ISO-aligned delivery"],

    },{
        id: "5",
        name: "Ashish Shetty",
        title: "Business Intelligence & Data Analytics Specialist | L&D Expert",
        role: "Business Intelligence & Data Analytics Specialist | L&D Expert",
        expertise: ["Business Intelligence", "learning and development professional"],
        bio: "Ashish Shetty is a seasoned Business Intelligence and learning and development professional with over 11 years of experience empowering students and professionals to unlock career success through data-driven skills. Specializing in Power BI, Tableau, and Prompt Engineering, Ashish is known for delivering practical, high-impact workshops and training programs across academic and corporate sectors.",
        location: "Mumbai, India",
        avatar: "/Team_Leaders_image/AshishShetty.png",
        linkedin: "https://www.linkedin.com/in/profashishshetty/",
        email: "mailto:hello@cinutedigital.com",
        highlights: ["10+ years in EdTech", "Built 1k+ careers", "ISO-aligned delivery"],

    },
]

export const teamData: TeamMember[] = [

    {
        id: "1",
        name: "Jayesh Patel",
        title: "Head of Programs (QA & Automation)",
        role: "Faculty",
        expertise: ["Selenium", "Playwright", "API Testing", "CI/CD"],
        bio: "Drives job-ready curriculum for Manual, Automation, and API Testing with real-world sprints and capstones.",
        location: "Pune, India",
        avatar: "/images/ami-khambata.png",
        linkedin: "https://www.linkedin.com/",
    },
    {
        id: "2",
        name: "Jayesh Patel",
        title: "Head of Programs (QA & Automation)",
        role: "Faculty",
        expertise: ["Selenium", "Playwright", "API Testing", "CI/CD"],
        bio: "Drives job-ready curriculum for Manual, Automation, and API Testing with real-world sprints and capstones.",
        location: "Pune, India",
        avatar: "/images/ami-khambata.png",
        linkedin: "https://www.linkedin.com/",
    },
    {
        id: "3",
        name: "Rhea Sharma",
        title: "Data Science Mentor",
        role: "Faculty",
        expertise: ["Python", "ML", "NLP", "Generative AI"],
        bio: "Mentors learners on ML fundamentals, model deployment, and prompt engineering for GenAI applications.",
        location: "Remote, India",
        avatar: "/images/ami-khambata.png",
    },
    {
        id: "4",
        name: "Arun Rao",
        title: "Industry Advisor (QA Strategy)",
        role: "Advisory",
        expertise: ["QA Strategy", "Test Architecture", "Agile"],
        bio: "Advises on QA strategy, governance, and enterprise-grade testing practices to align outcomes with hiring partner expectations.",
        location: "Bengaluru, India",
        avatar: "/images/ami-khambata.png",
    },
    {
        id: "5",
        name: "Neha Verma",
        title: "Program Operations Lead",
        role: "Operations",
        expertise: ["Student Success", "Placements", "Admissions"],
        bio: "Ensures a smooth learning journey—from enrollment to placement—with data-driven student success operations.",
        location: "Mumbai, India",
        avatar: "/images/ami-khambata.png",
    },

];

export const trainers: Trainer[] = [
    {
        id: 1,
        name: "Teshoo Rai",
        role: "Quality Analysis Engineer",
        avatar: "/Trainers_image/TeshooRai.png",
        bio: "A highly skilled Quality Analysis Engineer and Corporate Trainer, specialising in Software Development Life Cycle (SDLC) and Software Test Life Cycle (STLC).",
        yearsExp: 5,
        rating: 4.9,
        specialties: ["Corporate Trainer", "Software Development Life Cycle (SDLC)", "Software Test Life Cycle (STLC)", "Java Automation" , "Selenium"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
        linkedin: "http://linkedin.com/in/teshoo-rai-b56179237"
    },
    {
        id: 2,
        name: "Pooja Bombatkar",
        role: "Senior QA Mentor",
        avatar: "/Trainers_image/PoojaBombatkar.png",
        bio: "An ISTQB certified tester with more than 8-years of comprehensive experience of working in the field of software testing.",
        yearsExp: 8,
        rating: 4.9,
        specialties: ["Manual Testing", "Automation Testing", "API Testing", "Functional Testing", "System Testing"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
        linkedin: "https://www.linkedin.com/in/pooja-shinde-475076122",
    },
    {
        id: 3,
        name: "Aarav Mehta",
        role: "Senior QA Mentor",
        avatar: "/images/ami-khambata.png",
        bio: "Ex-Product QA Lead with 9+ years in Automation Testing for fintech & e-commerce; passionate about Playwright, CI/CD, and test strategies.",
        yearsExp: 9,
        rating: 4.9,
        specialties: ["Automation Testing", "Playwright", "API Testing", "CI/CD", "Test Strategy"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
    },
    {
        id: 4,
        name: "Aarav Mehta",
        role: "Senior QA Mentor",
        avatar: "/images/ami-khambata.png",
        bio: "Ex-Product QA Lead with 9+ years in Automation Testing for fintech & e-commerce; passionate about Playwright, CI/CD, and test strategies.",
        yearsExp: 9,
        rating: 4.9,
        specialties: ["Automation Testing", "Playwright", "API Testing", "CI/CD", "Test Strategy"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
    },
    {
        id: 5,
        name: "Aarav Mehta",
        role: "Senior QA Mentor",
        avatar: "/images/ami-khambata.png",
        bio: "Ex-Product QA Lead with 9+ years in Automation Testing for fintech & e-commerce; passionate about Playwright, CI/CD, and test strategies.",
        yearsExp: 9,
        rating: 4.9,
        specialties: ["Automation Testing", "Playwright", "API Testing", "CI/CD", "Test Strategy"],
        certifications: ["ISTQB CTFL", "Certified Scrum Master"],
        languages: ["English", "Hindi"],
        successStories: 120,
        slug: "aarav-mehta",
    },
];